### ISSUE TITLE
関数「h」の作成

### ISSUE THREAD

**Issue by taku-hira** [taku-hira/lamp_practice#1]
文字列を引数として渡すと、引数の文字列にhtmlエスケープを施した値を返り値として返す

・設計
関数を追加するファイル：function.php

htmlspecialchars関数を使用して引数に$strを渡してhtmlspecialchars処理して返す

**Comment by manatago** [comment]
modelページ、という表現はちょっと違いますが、modelのfunctions.phpの最後にでも

function h($str){
return htmlspecialchars($str,ENT_QUOTES,'UTF-8');
}

という感じで書いてみましょう。

**Comment by manatago** [comment]
modelのfunctions.phpの最後にでも

function h($str){
return htmlspecialchars($str,ENT_QUOTES,'UTF-8');
}

という感じで書いてみましょう。
